### PR TITLE
Feature/dagger2 final updates

### PR DESCRIPTION
**Pull request by eunix56**
Added dagger for search activity, created custom view model for search view model

### CODE REVIEW

**Comment by mayorJAY** [comment]
@eunix56 Pls which these PRs has the most updated version of this feature? I can see a number of repetitions in the 3 PRs
I don't think merging repetitions into development branch is healthy and infact, after merging the 1st PR, there is likely to be a number of merge conflicts with the others

**Comment by mayorJAY** [comment]
@eunix56 once again, please endeavor to test this feature well enough. I could see where you were using the same filter key repeatedly (SORT_BY_ACTIVITY) and this would lead to displaying the exact same set of data in the different fragments

**Comment by eunix56** [comment]
Oh okay then. That should be a mistake. I'll check and update the PRs.
Thank you

**Comment by mayorJAY** [comment]
@eunix56 As I suspected, this branch now have come conflicts. Try and resolve them. Thanks

**Comment by eunix56** [comment]
Okay then. I've updated this pull request. Thank you

**Comment by mayorJAY** [comment]
@eunix56 you did a great job. Big ups! 👍

**Comment by eunix56** [comment]
Thanks so much @mayorJAY/FlowOverStack
<reply@reply.github.com>. This
platform really helped me learn some new things. Thanks for your quick
response and guidance. It was nice working with you. Thanks again.

**Pull request merged**
