### PR TITLE
Animation

### PR DESCRIPTION
**Pull request by eunix56**
Added animation as the user scrolls up or down to the question list

### CODE REVIEW

**Comment by sfxjolugbohunmi** [comment]
Hey @eunix56 Are you currently participating in Hactoberfest?

**Comment by eunix56** [comment]
Yes I am

**Comment by mayorJAY** [comment]
@eunix56 did you test this feature you added? 
Does it work?

**Comment by eunix56** [comment]
Yes I tested it and it works. Each list item slides in as you scroll either
up or down

**Comment by mayorJAY** [comment]
Great!

**Comment by eunix56** [comment]
Oh okay, thank you. Hope you've tested it and you like it

**Comment by eunix56** [comment]
Can you help tag the merged PR with the hacktoberfest-accepted label? Thank
you

**Comment by eunix56** [comment]
Hi Joseph, I've submitted three more pull requests adding the dagger2
implementation to the app. Please can you help check, approve and add the
hacktoberfest-accepted label to them? I've tested it and it works well.
Thank you

**Pull request merged**
